version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      
   pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - app/build/outputs/apk/app-debug.apk
